[DEFAULT]
# All sections below are required unless otherwise specified.
# See https://github.com/fastai/nbdev/blob/master/settings.ini for examples.

### Python library ###
repo = bioMONAI
lib_name = %(repo)s
version = 0.0.1
min_python = 3.7
license = apache2
black_formatting = False

### nbdev ###
doc_path = _docs
lib_path = bioMONAI
nbs_path = nbs
recursive = True
tst_flags = notest
put_version_in_init = True

### Docs ###
branch = main
custom_sidebar = False
doc_host = https://%(user)s.github.io
doc_baseurl = /%(repo)s
git_url = https://github.com/%(user)s/%(repo)s
title = %(lib_name)s

### PyPI ###
audience = Developers
author = bmandracchia
author_email = biagio.mandracchia@uva.es
copyright = 2024 onwards, %(author)s
description = Deep learning library biomedical data built on top of MONAI
keywords = monai pytorch nbdev jupyter notebook python
language = English
status = 3
user = bmandracchia

### Optional ###
requirements =  pandas aicsimageio==4.14 h5py==3.11 plotly==5.23 fastai==2.7.12 monai==1.2.0 pytorch==2.8.1 pytorch-cuda==11.8 torchio==0.18.91 xlrd>=1.2.0 scikit-image==0.19.3 imagedata==2.1.3 pooch==1.8.2 mamba-ssm==2.2.2
dev_requirements = ipywidgets nbdev-numpy nbdev-stdlib pandas matplotlib nbclassic 
# console_scripts =