# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bioMONAI',
                'doc_host': 'https://bmandracchia.github.io',
                'git_url': 'https://github.com/bmandracchia/bioMONAI',
                'lib_path': 'bioMONAI'},
  'syms': {'bioMONAI.core': {'bioMONAI.core.foo': ('core.html#foo', 'bioMONAI/core.py')}}}
