"""Event handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_callbacks.ipynb.

# %% auto 0
__all__ = ['MeanLossGraphCallback']

# %% ../nbs/07_callbacks.ipynb 3
from fastai.callback.training import ShortEpochCallback, GradientAccumulation
from fastai.callback.tracker import  EarlyStoppingCallback, SaveModelCallback, ReduceLROnPlateau
from fastai.callback.schedule import ParamScheduler, SchedCos, SchedExp, SchedLin, SchedNo
from fastai.callback.core import Callback
import matplotlib.pyplot as plt


# %% ../nbs/07_callbacks.ipynb 5
class MeanLossGraphCallback(Callback):
    def __init__(self):
        self.train_losses = []
        self.valid_losses = []
    
    def before_fit(self):
        # Reset the losses at the beginning of the training
        self.train_losses.clear()
        self.valid_losses.clear()
    
    def after_epoch(self):
        # Compute the mean loss of the current epoch for both training and validation
        train_loss = sum(self.learn.recorder.losses) / len(self.learn.recorder.losses)
        valid_loss = self.learn.recorder.values[-1][0]  # Validation loss after epoch
        
        # Append mean losses for plotting later
        self.train_losses.append(train_loss)
        self.valid_losses.append(valid_loss)
    
    def after_fit(self):
        # Plot the mean loss after training is complete
        plt.figure(figsize=(8, 5))
        plt.plot(self.train_losses, label='Train Mean Loss')
        plt.plot(self.valid_losses, label='Validation Mean Loss')
        plt.xlabel('Epoch')
        plt.ylabel('Mean Loss')
        plt.title('Mean Loss per Epoch')
        plt.legend()
        plt.show()

