"""Event handlers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_callbacks.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_callbacks.ipynb 3
from fastai.callback.training import ShortEpochCallback, GradientAccumulation
from fastai.callback.tracker import  EarlyStoppingCallback, SaveModelCallback, ReduceLROnPlateau
from fastai.callback.schedule import ParamScheduler, SchedCos, SchedExp, SchedLin, SchedNo

