# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['attributesFromDict']

# %% ../nbs/00_core.ipynb 4
from torch import Tensor as torchTensor
from torch import tensor
from monai.data import MetaTensor

import torch.nn.functional as F

from random import randint

# %% ../nbs/00_core.ipynb 5
from torch import squeeze as torchsqueeze
from torch import max as torchmax
from torch import from_numpy as torch_from_numpy

# %% ../nbs/00_core.ipynb 6
from fastai.vision.all import BypassNewMeta, DisplayedTransform
from fastai.data.all import delegates, hasattrs, Path, List, L, typedispatch

# %% ../nbs/00_core.ipynb 8
# maybe this should be changed for fastai store_attr()
def attributesFromDict(d):
    self = d.pop('self')
    for n, v in d.items():
        setattr(self, n, v)
