# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['attributesFromDict', 'img2float', 'img2Tensor']

# %% ../nbs/00_core.ipynb 4
from torch import Tensor as torchTensor
from torch import tensor
from monai.data import MetaTensor

import torch.nn.functional as F

from random import randint

from skimage import util
from skimage.data import cells3d

# %% ../nbs/00_core.ipynb 5
from torch import squeeze as torchsqueeze, max as torchmax, from_numpy as torch_from_numpy, device as torch_device
from torch.cuda import is_available as is_cuda_available

# %% ../nbs/00_core.ipynb 6
from collections.abc import MutableSequence
from typing import MutableSequence
    
from fastai.callback.core import Callback
from fastai.data.all import DataLoaders, Path, trainable_params, delegates, hasattrs, Path, List, L, typedispatch
from fastai.optimizer import Adam, OptimWrapper, Optimizer
from fastai.vision.all import BypassNewMeta, DisplayedTransform, store_attr, DataBlock, Learner, ShowGraphCallback, CSVLogger


# %% ../nbs/00_core.ipynb 10
# maybe this should be changed for fastai store_attr()
def attributesFromDict(d):
    self = d.pop('self')
    for n, v in d.items():
        setattr(self, n, v)

# %% ../nbs/00_core.ipynb 12
def img2float(image, force_copy=False):
    return util.img_as_float(image, force_copy=force_copy)

# %% ../nbs/00_core.ipynb 13
def img2Tensor(image):
    return torchTensor(img2float(image))
