"""Data classes and functions"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto 0
__all__ = ['MetaResolver', 'BioImageBase', 'BioImage', 'BioImageStack', 'BioImageProject', 'BioImageMulti', 'Tensor2BioImage',
           'BioImageBlock', 'BioDataBlock', 'BioDataLoaders', 'get_gt', 'get_target', 'get_noisy_pair', 'show_batch',
           'show_results', 'extract_patches', 'save_patches_grid', 'extract_random_patches', 'save_patches_random']

# %% ../nbs/01_data.ipynb 4
import os
import numpy as np
import pandas as pd
import h5py
from tqdm import tqdm 
import random

from .core import MetaTensor, torchTensor, BypassNewMeta, DisplayedTransform, torchsqueeze, Path, List, L, torchmax, randint, typedispatch
from .io import image_reader
from .visualize import show_images_grid, show_multichannel

from fastai.data.all import DataLoaders, delegates, RegexLabeller, is_listy, ColReader, ColSplitter
from fastai.vision.all import DataBlock, CategoryBlock, MultiCategoryBlock, RegressionBlock, TfmdDL, get_image_files, TransformBlock, get_grid, merge, show_image, RandomSplitter, GrandparentSplitter, partial, parent_label

# %% ../nbs/01_data.ipynb 5
class MetaResolver(type(torchTensor), metaclass=BypassNewMeta):
    """
    A class to bypass metaclass conflict:
    https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/data/batch.html
    """
    pass
    

# %% ../nbs/01_data.ipynb 6
class BioImageBase(MetaTensor, metaclass=MetaResolver):
    """
    A class that represents an image object.
    Metaclass casts `x` to this class if it is of type `cls._bypass_type`.
    """
    
    _bypass_type = torchTensor  # The type that bypasses image loading
    _show_args = {'cmap': 'gray'}  # Default arguments for image display
    resample, reorder = None, False  # Default resample and reorder settings
    affine_matrix = None  # Default affine matrix for image transformation

    @classmethod
    def create(cls, fn: (Path, str, List, torchTensor), **kwargs) -> torchTensor: 
        """
        Opens an image and casts it to BioImageBase object.
        If `fn` is a torchTensor, it's cast to BioImageBase object.

        Args:
            fn : (Path, str, torchTensor)
                Image path or a 4D torchTensor.
            kwargs : dict
                Additional parameters for the medical image reader.

        Returns:
            torchTensor : A 4D tensor as a BioImageBase object.
        """
        if isinstance(fn, torchTensor):
            return cls(fn)

        return image_reader(fn, dtype=cls, resample=cls.resample, reorder=cls.reorder)

    @classmethod
    def item_preprocessing(cls, resample: (List, int, tuple), reorder: bool):
        """
        Changes the values for the class variables `resample` and `reorder`.

        Args:
            resample : (List, int, tuple)
                A list with voxel spacing.
            reorder : bool
                Whether to reorder the data to be closest to canonical (RAS+) orientation.
        """
        cls.resample = resample
        cls.reorder = reorder

    def show(self, ctx=None, figsize: int = None, ncols: int = 10, title=None, **kwargs):
        """
        Plots 2D slices of a 3D image alongside a prior specified axis.

        Args:
            ctx : Context to use for the display. Defaults to None.
            figsize: Size of the figure. Defaults to None.
            ncols: Number of columns in the grid. Defaults to 10.
            **kwargs : Additional keyword arguments passed to plt.imshow.

        Returns:
            Shown image.
        """
        return show_images_grid(self, ctx=ctx, ncols=ncols, title=[title], **merge(self._show_args, kwargs))
    
    def as_tensor(self) -> torchTensor:
        """
        Return the `MetaTensor` as a `torchTensor`.
        It is OS dependent as to whether this will be a deep copy or not.
        """
        return self.as_subclass(torchTensor)

    def __repr__(self) -> str:
        """Returns the string representation of the ImageBase instance."""
        return f"BioImageBase{self.as_tensor().__repr__()[6:]}"

# %% ../nbs/01_data.ipynb 7
class BioImage(BioImageBase):
    """Subclass of BioImageBase that represents 2D and 3D image objects."""
    _show_args = {'cmap':'gray'}
    
    @classmethod
    def create(cls, fn: (Path, str, L, list, torchTensor), **kwargs) -> torchTensor: 
        """
        Opens an image and casts it to BioImageBase object.
        If `fn` is a torchTensor, it's cast to BioImageBase object.

        Args:
            fn : (Path, str, torchTensor)
                Image path or a 4D torchTensor.
            kwargs : dict
                Additional parameters for the medical image reader.

        Returns:
            torchTensor : A 2D or 3D tensor as a BioImage object.
        """
        if isinstance(fn, torchTensor):
            return cls(fn)

        return torchsqueeze(image_reader(fn, dtype=cls, resample=cls.resample, reorder=cls.reorder), 1)
    
    def show(self, ctx=None, **kwargs):
        "Show image using `merge(self._show_args, kwargs)`"
        return show_image(self, ctx=ctx, **merge(self._show_args, kwargs))
    
    def __repr__(self) -> str:
        """Returns the string representation of the ImageBase instance."""
    #     return f'{self.__class__.__name__} shape={"x".join([str(d) for d in self.shape])}'
        return f"BioImage{self.as_tensor().__repr__()[6:]}"

# %% ../nbs/01_data.ipynb 9
class BioImageStack(BioImageBase):
    """Subclass of BioImageBase that represents a 3D image object."""
    
    def __repr__(self) -> str:
        """Returns the string representation of the ImageBase instance."""
        return f"BioImageStack{self.as_tensor().__repr__()[6:]}"

# %% ../nbs/01_data.ipynb 11
class BioImageProject(BioImageBase):
    """Subclass of BioImageBase that represents a 3D image stack as a 2D image object using maximum intensity projection."""
    _show_args = {'cmap':'gray'}
    
    @classmethod
    def create(cls, fn: (Path, str, L, list, torchTensor), **kwargs) -> torchTensor: 
        """
        Opens an image and casts it to BioImageBase object.
        If `fn` is a torchTensor, it's cast to BioImageBase object.

        Args:
            fn : (Path, str, torchTensor)
                Image path or a 4D torchTensor.
            kwargs : dict
                Additional parameters for the medical image reader.

        Returns:
            torchTensor : A 3D tensor as a BioImage object.
        """
        if isinstance(fn, torchTensor):
            return cls(fn)

        img = image_reader(fn, dtype=cls, resample=cls.resample, reorder=cls.reorder)
        return torchmax(img, dim=1)[0]  # Taking the maximum intensity projection along axis 1
    
    def show(self, ctx=None, **kwargs):
        "Show image using `merge(self._show_args, kwargs)`"
        return show_image(self, ctx=ctx, **merge(self._show_args, kwargs))
    
    def __repr__(self) -> str:
        """Returns the string representation of the ImageBase instance."""
        return f"BioImage{self.as_tensor().__repr__()[6:]}"

# %% ../nbs/01_data.ipynb 13
class BioImageMulti(BioImageBase):
    """Subclass of BioImageBase that represents a multi-channel 2D image object."""
    
    @classmethod
    def create(cls, fn: (Path, str, L, list, torchTensor), **kwargs) -> torchTensor: 
        """
        Opens an image and casts it to BioImageBase object.
        If `fn` is a torchTensor, it's cast to BioImageBase object.

        Args:
            fn : (Path, str, torchTensor)
                Image path or a 4D torchTensor.
            kwargs : dict
                Additional parameters for the medical image reader.

        Returns:
            torchTensor : A 3D tensor as a BioImage object.
        """
        if isinstance(fn, torchTensor):
            return cls(fn)

        return torchsqueeze(image_reader(fn, dtype=cls, resample=cls.resample, reorder=cls.reorder))
    
    def show(self, ctx=None, **kwargs):
        "Show image using `merge(self._show_args, kwargs)`"
        return show_multichannel(self, ctx=ctx, **merge(self._show_args, kwargs))
    
    def __repr__(self) -> str:
        """Returns the string representation of the ImageBase instance."""
        return f"BioImageMulti{self.as_tensor().__repr__()[6:]}"
        

# %% ../nbs/01_data.ipynb 18
class Tensor2BioImage(DisplayedTransform):
    def __init__(self, cls:BioImageBase=BioImageStack):
        self.cls = cls

    def encodes(self, o):
        if isinstance(o, MetaTensor):
            # return self.cls(o.clone(), affine=o.affine, meta=o.meta)
            return self.cls(o.clone(), meta=o.meta)
        
        if isinstance(o, torchTensor):
            return self.cls(o)

# %% ../nbs/01_data.ipynb 20
def BioImageBlock(cls:BioImageBase=BioImage):
    "A `TransformBlock` for images of `cls`"
    return TransformBlock(type_tfms=[cls.create, Tensor2BioImage(cls)]) # IntToFloatTensor

# %% ../nbs/01_data.ipynb 21
class BioDataBlock(DataBlock):
    def __init__(self, 
            blocks:list=(BioImageBlock(cls=BioImage), BioImageBlock(cls=BioImage)), # One or more `TransformBlock`s
            dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `block`'s dl_type or`TfmdDL`
            get_items=get_image_files,
            get_y=None,
            get_x=None,
            getters:list=None, # Getter functions applied to results of `get_items`
            n_inp:int=None, # Number of inputs
            item_tfms:list=None, # `ItemTransform`s, applied on an item 
            batch_tfms:list=None, # `Transform`s or `RandTransform`s, applied by batch
            **kwargs, 
        ):
        super().__init__(
            blocks=blocks, 
            dl_type=dl_type, 
            get_items=get_items,
            get_y=get_y,
            get_x=get_x,
            getters=getters, 
            n_inp=n_inp, 
            item_tfms=item_tfms, 
            batch_tfms=batch_tfms,
            **kwargs,
            )
        

# %% ../nbs/01_data.ipynb 22
class BioDataLoaders(DataLoaders):
    "Basic wrapper around several `DataLoader`s with factory methods for biomedical imaging problems"
    @classmethod
    @delegates(DataLoaders.from_dblock)
    def from_source(data_source, show_summary:bool=False, **kwargs):
        """
        Create and return a DataLoader from a BioDataBlock using provided keyword arguments.
        
        Args:
            data_source (any): The source of the data to be loaded by the dataloader.
                                This can be any type that is compatible with the dataloading method 
                                specified in kwargs (e.g., paths, datasets).
            show_summary (bool, optional): If True, print a summary of the BioDataBlock after creation.
                                        Default is False.
            **kwargs: Additional keyword arguments to configure the DataLoader and BioDataBlock.
                    Supported keys include: 'blocks', 'dl_type', 'get_items', 'get_y', 
                    'get_x', 'getters', 'n_inp', 'item_tfms', 'batch_tfms'.
        
        Returns:
            DataLoader: A PyTorch DataLoader object populated with the data from the BioDataBlock.
                        If show_summary is True, it also prints a summary of the datablock after creation.
        
        Example:
            >>> dataloader = BioDataLoaders.from_source(data_path, show_summary=True, blocks='train', dl_type='ImageDataLoader')
        """
        # Define the keys for BioDataBlock operations
        datablock_ops_keys = ['blocks','dl_type','get_items','get_y','get_x','getters','n_inp','item_tfms','batch_tfms']
        
        # Filter and assign kwargs to datablock_ops dictionary for BioDataBlock initialization
        datablock_ops = {key: value for key, value in kwargs.items() if key in datablock_ops_keys}
        
        # Filter and assign remaining kwargs to dataloader_ops dictionary for DataLoader creation
        dataloader_ops = {key: value for key, value in kwargs.items() if key not in datablock_ops_keys}
        
        # Initialize BioDataBlock with specified operations
        datablock = BioDataBlock(**datablock_ops)
        
        # Create and return the DataLoader from the initialized BioDataBlock
        dataloder = datablock.dataloaders(data_source, **dataloader_ops)
        
        # Optionally print a summary of the BioDataBlock if show_summary is True
        if show_summary:
            print(datablock.summary(data_source))
        
        return dataloder

    @classmethod
    @delegates(from_source)
    def from_folder(cls, path, get_target_fn, train='train', valid='valid', valid_pct=None, seed=None, item_tfms=None,
                    batch_tfms=None, img_cls=BioImage, target_img_cls=BioImage, **kwargs):
        "Create from dataset in `path` with `train` and `valid` subfolders (or provide `valid_pct`)"
        splitter = GrandparentSplitter(train_name=train, valid_name=valid) if valid_pct is None else RandomSplitter(valid_pct, seed=seed)
        get_items = get_image_files if valid_pct else partial(get_image_files, folders=[train, valid])
        ops = { 
            'blocks':       (BioImageBlock(img_cls), BioImageBlock(target_img_cls)),
            'get_items':    get_items,
            'splitter':     splitter,
            'get_y':        get_target_fn,
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source(path, **ops, **kwargs)
    
    @classmethod
    @delegates(from_source)
    def from_df(cls, df, path='.', valid_pct=0.2, seed=None, fn_col=0, folder=None, suff='', target_col=1, target_folder=None, target_suff='',
                valid_col=None, item_tfms=None, batch_tfms=None, target_img_cls=BioImage, img_cls=BioImage, **kwargs):
        "Create from `df` using `fn_col` and `target_col`"
        pref = f'{Path(path) if folder is None else Path(path)/folder}{os.path.sep}'
        target_pref = f'{pref if folder is None else Path(path)/target_folder}{os.path.sep}'
        splitter = RandomSplitter(valid_pct, seed=seed) if valid_col is None else ColSplitter(valid_col)        
        ops = { 
            'blocks':       (BioImageBlock(img_cls), BioImageBlock(target_img_cls)),
            'splitter':     splitter,
            'get_x':        ColReader(fn_col, pref=pref, suff=suff),
            'get_y':        ColReader(target_col, pref=target_pref, suff=target_suff),
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source(df, **ops, **kwargs)
    
    @classmethod
    @delegates(from_df)
    def from_csv(cls, path, csv_fname='train.csv', header='path', delimiter=None, quoting=0, **kwargs):
        "Create from `path/csv_fname` using `fn_col` and `target_col`"
        df = pd.read_csv(Path(path)/csv_fname, header=header, delimiter=delimiter, quoting=quoting)
        return cls.from_df(df, path=path, **kwargs)
    
    @classmethod
    @delegates(from_source)
    def multi_from_df(cls, df, path='', path_col=0, folder=None, valid_pct=0.2, seed=None, input_col=1, input_pref='', input_suff='', target_col=2, target_pref='', target_suff='',
                valid_col=None, item_tfms=None, batch_tfms=None, target_img_cls=BioImage, img_cls=BioImage, **kwargs):
        "Create from `df` using `fn_col` and `target_col`"
        pref = f'{Path(path) if folder is None else Path(path)/folder}{os.path.sep}'
        splitter = RandomSplitter(valid_pct, seed=seed) if valid_col is None else ColSplitter(valid_col)      
        x_suff = ColReader(input_col, pref=input_pref, suff=input_suff)
        y_suff = ColReader(target_col, pref=target_pref, suff=target_suff)
        ops = { 
            'blocks':       (BioImageBlock(img_cls), BioImageBlock(target_img_cls)),
            'splitter':     splitter,
            'get_x':        ColReader(path_col, pref=pref, suff=x_suff),
            'get_y':        ColReader(path_col, pref=pref, suff=y_suff),
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source(df, **ops, **kwargs)
    
    @classmethod
    @delegates(multi_from_df)
    def multi_from_csv(cls, path, csv_fname='train.csv', header='path', delimiter=None, quoting=0, **kwargs):
        "Create from `path/csv_fname` using `fn_col` and `target_col`"
        df = pd.read_csv(Path(path)/csv_fname, header=header, delimiter=delimiter, quoting=quoting)
        return cls.multi_from_df(df, path=path, **kwargs)
    
    @classmethod
    @delegates(from_source)
    def class_from_folder(cls, path, train='train', valid='valid', valid_pct=None, seed=None, vocab=None, item_tfms=None,
                    batch_tfms=None, img_cls=BioImage, **kwargs):
        "Create from dataset in `path` with `train` and `valid` subfolders (or provide `valid_pct`)"
        splitter = GrandparentSplitter(train_name=train, valid_name=valid) if valid_pct is None else RandomSplitter(valid_pct, seed=seed)
        get_items = get_image_files if valid_pct else partial(get_image_files, folders=[train, valid])
        ops = { 
            'blocks':       (BioImageBlock(img_cls), CategoryBlock(vocab=vocab)),
            'get_items':    get_items,
            'splitter':     splitter,
            'get_y':        parent_label,
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source(path, **ops, **kwargs)

    @classmethod
    @delegates(from_source)
    def class_from_path_func(cls, path, fnames, label_func, valid_pct=0.2, seed=None, item_tfms=None, batch_tfms=None, 
                       img_cls=BioImage, **kwargs):
        "Create from list of `fnames` in `path`s with `label_func`"
        ops = { 
            'blocks':       (BioImageBlock(img_cls), CategoryBlock),
            'splitter':     RandomSplitter(valid_pct, seed=seed),
            'get_y':        label_func,
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source(fnames, **ops, **kwargs)

    @classmethod
    def class_from_path_re(cls, path, fnames, pat, **kwargs):
        "Create from list of `fnames` in `path`s with re expression `pat`"
        return cls.class_from_path_func(path, fnames, RegexLabeller(pat), **kwargs)

    @classmethod
    @delegates(from_source)
    def class_from_df(cls, df, path='.', valid_pct=0.2, seed=None, fn_col=0, folder=None, suff='', label_col=1, label_delim=None,
                y_block=None, valid_col=None, item_tfms=None, batch_tfms=None, img_cls=BioImage, **kwargs):
        "Create from `df` using `fn_col` and `label_col`"
        pref = f'{Path(path) if folder is None else Path(path)/folder}{os.path.sep}'
        if y_block is None:
            is_multi = (is_listy(label_col) and len(label_col) > 1) or label_delim is not None
            y_block = MultiCategoryBlock if is_multi else CategoryBlock
        splitter = RandomSplitter(valid_pct, seed=seed) if valid_col is None else ColSplitter(valid_col)        
        ops = { 
            'blocks':       (BioImageBlock(img_cls), y_block),
            'splitter':     splitter,
            'get_x':        ColReader(fn_col, pref=pref, suff=suff),
            'get_y':        ColReader(label_col, label_delim=label_delim),
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source(df, **ops, **kwargs)
    
    @classmethod
    def class_from_csv(cls, path, csv_fname='labels.csv', header='infer', delimiter=None, quoting=0, **kwargs):
        "Create from `path/csv_fname` using `fn_col` and `label_col`"
        df = pd.read_csv(Path(path)/csv_fname, header=header, delimiter=delimiter, quoting=quoting)
        return cls.class_from_df(df, path=path, **kwargs)

    @classmethod
    @delegates(from_source)
    def class_from_lists(cls, path, fnames, labels, valid_pct=0.2, seed:int=None, y_block=None, item_tfms=None, batch_tfms=None,
                   img_cls=BioImage, **kwargs):
        "Create from list of `fnames` and `labels` in `path`"
        if y_block is None:
            y_block = MultiCategoryBlock if is_listy(labels[0]) and len(labels[0]) > 1 else (
                RegressionBlock if isinstance(labels[0], float) else CategoryBlock)
        ops = { 
            'blocks':       (BioImageBlock(img_cls), y_block),
            'splitter':     RandomSplitter(valid_pct, seed=seed),
            'item_tfms':    item_tfms,
            'batch_tfms':   batch_tfms,
            'path':         path,
            }
        return cls.from_source((fnames, labels), **ops, **kwargs)

BioDataLoaders.class_from_csv = delegates(to=BioDataLoaders.class_from_df)(BioDataLoaders.class_from_csv)
BioDataLoaders.class_from_path_re = delegates(to=BioDataLoaders.class_from_path_func)(BioDataLoaders.class_from_path_re)


# %% ../nbs/01_data.ipynb 24
from fastai.vision.all import get_image_files

# %% ../nbs/01_data.ipynb 25
def get_gt(path_gt, gt_file_name="avg50.png"):
    """
    Constructs a path to a ground truth file based on the given `path_gt` and `gt_file_name`.
    
    This function uses a lambda function to create a new path by appending `gt_file_name` to 
    the parent directory of the input file, as specified by `path_gt`.
    
    Parameters:
        path_gt (str or Path): The base directory where the ground truth files are stored, 
                               or a file path from which to derive the parent directory.
        gt_file_name (str, optional): The name of the ground truth file. Defaults to "avg50.png".
    
    Returns:
        callable: A function that takes a single argument (a filename) and returns a Path object 
                   representing the full path to the ground truth file. When called with a filename, 
                   this function constructs the path by combining `path_gt` or the parent directory of 
                   the filename with `gt_file_name`.
    
    Example:
        If you have a file path like "./data/images/123/image.png" and you want to find the corresponding
        ground truth file, you might call get_gt("./data/gt_images")(path). This would return a Path object 
        pointing to "./data/gt_images/123/avg50.png".
    """
    
    # Convert path_gt to Path object if it's a string
    path_gt = Path(path_gt)
    
    # Define the lambda function that constructs the full path
    _fn = lambda fn: path_gt / f"{Path(fn).parent}" / gt_file_name
    
    return _fn


# %% ../nbs/01_data.ipynb 26
def get_target(path, same_filename=True, target_file_prefix="target", signal_file_prefix="signal"):
    """
    Constructs and returns functions for generating file paths to "target" files based on given input parameters.
    
    This function defines two nested helper functions within its scope: \n
        - `construct_target_filename(file_name)`: Constructs a target file name by inserting the specified prefix into the original file name.
        - `generate_target_path(file_name)`: Generates a path to the target file based on whether `same_filename` is set to True or False.
    
    The main function returns the appropriate helper function based on the value of `same_filename`.
    
    Parameters: \n
        path (str): The base directory where the files are located. This should be a string representing an absolute or relative path.
        same_filename (bool, optional): If True, the target file name will match the original file name; otherwise, it will use the specified prefix. Defaults to True.
        target_file_prefix (str, optional): The prefix to insert into the target file name if `same_filename` is False. Defaults to "target".
        signal_file_prefix (str, optional): The prefix used in the original file names that should be replaced by the target prefix. Defaults to "signal".
    
    Returns: \n
        callable: A function that takes a file name as input and returns its corresponding target file path based on the specified parameters.
    
    """
    # Define a function to construct the target file name based on input parameters
    def construct_target_filename(file_name):
        # Split the file name based on the signal file prefix
        parts = file_name.split(signal_file_prefix)
        
        # Construct the target file name by inserting the target file prefix
        target_file_name = parts[0] + target_file_prefix + parts[1]
        
        return target_file_name
    
    # Define a function to generate the target file path based on the given file name
    def generate_target_path(file_name):
        # Extract the base file name
        base_filename = os.path.basename(file_name)
        
        # If same_filename is True, simply return the path joined with the base file name
        if same_filename:
            return Path(path) / base_filename
        
        # If same_filename is False, construct the target file name and return the path joined with it
        target_filename = construct_target_filename(base_filename)
        return Path(path) / target_filename
    
    # Return the appropriate function based on the value of same_filename
    return generate_target_path



# %% ../nbs/01_data.ipynb 30
def get_noisy_pair(fn):
    """
    Get another "noisy" version of the input file by selecting a file from the same directory.
    
    This function first retrieves all image files in the directory of the input file `fn` (excluding subdirectories). 
    It then selects one of these files at random, ensuring that it is not the original file itself to avoid creating a trivial "noisy" pair.
    
    Parameters: \n
        fn (Path or str): The path to the original image file. This should be a Path object but accepts string inputs for convenience.
    
    Returns: \n
        Path: A Path object pointing to the selected noisy file.
    
    """
    
    # Convert fn to Path object if it's not already one
    fn = Path(fn)
    
    # Get all image files in the parent directory of the input file
    tmp = get_image_files(fn.parent, recurse=False)
    
    # Select a random file from the list, ensuring it's not the original file
    fn2 = tmp[randint(0, len(tmp) - 1)]
    while fn2 == fn:
        fn2 = tmp[randint(0, len(tmp) - 1)]
    
    return fn2


# %% ../nbs/01_data.ipynb 33
from fastai.vision.all import TensorCategory

# %% ../nbs/01_data.ipynb 34
@typedispatch
def show_batch(x: BioImageBase,      # The input image data.
               y: TensorCategory,    # The target data (categorical labels).
               samples,              # List of sample indices to display.
               ctxs=None,            # List of contexts for displaying images. If None, create new ones using get_grid().
               max_n: int=10,        # Maximum number of samples to display. Default is 10.
               nrows: int=None,      # Number of rows in the grid if ctxs are not provided.
               ncols: int=None,      # Number of columns in the grid if ctxs are not provided.
               figsize: tuple=None,  # Figure size for the image display.
               **kwargs,             # Additional keyword arguments to pass to the show method of BioImageBase.
               ):
    """
    Display a batch of images with their corresponding labels as titles.
    
    Returns:
        List[Context]: A list of contexts after displaying the images and their labels.
    """
    # If ctxs are not provided, create new ones using get_grid()
    if ctxs is None: 
        ctxs = get_grid(min(len(samples), max_n), nrows=nrows, ncols=ncols, figsize=figsize)
    
    # Flatten the context in case it returns as an array
    if isinstance(ctxs, np.ndarray):
        ctxs = ctxs.flatten()
    
    # Extract the input images and the corresponding labels
    xs, ys = samples.itemgot(0), samples.itemgot(1)

    # Loop through the images and labels
    for i in range(len(xs)):
        # Display each input image
        ctxs[i] = xs[i].show(ctx=ctxs[i], title=f"Label: {ys[i]}", **kwargs)
    
    return ctxs





# %% ../nbs/01_data.ipynb 36
@typedispatch
def show_results(x: BioImageBase, # The input image data.
                 y: BioImageBase, # The target label data.
                 samples, # List of sample indices to display.
                 outs, # List of output predictions corresponding to the samples.
                 ctxs=None, # List of contexts for displaying images. If None, create new ones using get_grid().
                 max_n=10, # Maximum number of samples to display.
                 figsize=None, # Figure size for the image display.
                 **kwargs, # Additional keyword arguments to pass to the show method of BioImageBase.
                 ):
    """
    Display a batch of input images along with their predicted and target labels.
   
    Returns: \n
        List[Context]: A list of contexts after displaying the images and labels.
    """
    # If ctxs are not provided, create new ones using get_grid() with a specific title and size
    if ctxs is None: 
        ctxs = get_grid(3 * min(len(samples), max_n), ncols=3, figsize=figsize, title='Input/Target/Prediction')
    
    # Loop through the images and display them in a specific context for input (x) and output predictions (outs)
    for i in range(2):
        ctxs[i::3] = [b.show(ctx=c, **kwargs) for b, c, _ in zip(samples.itemgot(i), ctxs[i::3], range(max_n))]
    
    # Display the target labels (y) in a specific context after the input images
    ctxs[2::3] = [b.show(ctx=c, **kwargs) for b, c, _ in zip(outs.itemgot(0), ctxs[2::3], range(max_n))]
    
    return ctxs


# %% ../nbs/01_data.ipynb 39
def extract_patches(data, patch_size, overlap):
    """
    Extracts n-dimensional patches from the input data.
    
    Parameters:
    - data: numpy array of the input data (n-dimensional).
    - patch_size: tuple of integers defining the size of the patches in each dimension.
    - overlap: float (between 0 and 1) indicating overlap between patches.
    
    Returns:
    - A list of patches as numpy arrays.
    """
    data_shape = data.shape
    strides = tuple(int(p * (1 - overlap)) for p in patch_size)  # Calculate the stride for each dimension
    
    # Compute the range of indices for each dimension
    slices = [range(0, data_shape[i] - patch_size[i] + 1, strides[i]) for i in range(len(patch_size))]
    
    # Generate patches
    patches = []
    for indices in np.ndindex(*[len(s) for s in slices]):
        # Create slices for each dimension
        patch_slices = tuple(slice(slices[dim][idx], slices[dim][idx] + patch_size[dim]) for dim, idx in enumerate(indices))
        patches.append(data[patch_slices])
    
    return patches

# %% ../nbs/01_data.ipynb 40
def save_patches_grid(data_folder, gt_folder, output_folder, patch_size, overlap):
    """
    Loads n-dimensional data from data_folder and gt_folder, generates patches, and saves them into individual HDF5 files.
    Each HDF5 file will have datasets with the structure X/patch_idx and y/patch_idx.
    
    Parameters:
    - data_folder: Path to the folder containing data files (n-dimensional data).
    - gt_folder: Path to the folder containing ground truth (gt) files (n-dimensional data).
    - output_folder: Path to the folder where the HDF5 files will be saved.
    - patch_size: tuple of integers defining the size of the patches.
    - overlap: float (between 0 and 1) defining the overlap between patches.
    """
    
    # Ensure output folder exists
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    # Ensure the folders contain the same number of files
    data_files = sorted([f for f in os.listdir(data_folder) if f.endswith(('.npy', '.npz', '.png', '.tif', '.tiff'))])
    gt_files = sorted([f for f in os.listdir(gt_folder) if f.endswith(('.npy', '.npz', '.png', '.tif', '.tiff'))])
    
    print(data_files)
    
    if len(data_files) != len(gt_files):
        raise ValueError("The number of files in data_folder and gt_folder must be the same.")
    
    # Loop through the files in the folders with progress bar
    for data_file_name, gt_file_name in tqdm(zip(data_files, gt_files), total=len(data_files), desc="Processing files"):
        data_file_path = os.path.join(data_folder, data_file_name)
        gt_file_path = os.path.join(gt_folder, gt_file_name)
        
        # Load the images 
        data = np.array(image_reader(data_file_path)[0])
        gt = np.array(image_reader(gt_file_path)[0])
        
        if data.shape != gt.shape:
            raise ValueError(f"Shape mismatch between {data_file_name} and {gt_file_name}")
        
        # Extract patches from both datasets
        data_patches_nd = extract_patches(data, patch_size, overlap)
        gt_patches_nd = extract_patches(gt, patch_size, overlap)
        
        # Create a new HDF5 file for this pair of files
        hdf5_filename = os.path.join(output_folder, f"{os.path.splitext(data_file_name)[0]}.h5")
        
        with h5py.File(hdf5_filename, 'w') as hf:
            # Store each patch in a separate dataset with a progress bar for each file
            for patch_idx, (data_patch, gt_patch) in enumerate(tqdm(zip(data_patches_nd, gt_patches_nd), 
                                                                    total=len(data_patches_nd), 
                                                                    desc=f"Saving patches for {data_file_name}", 
                                                                    leave=False)):
                hf.create_dataset(f'X/{patch_idx}', data=data_patch)
                hf.create_dataset(f'y/{patch_idx}', data=gt_patch)
        

# %% ../nbs/01_data.ipynb 44
def extract_random_patches(data, patch_size, num_patches):
    """
    Extracts a specified number of random n-dimensional patches from the input data.
    
    Parameters:
    - data: numpy array of the input data (n-dimensional).
    - patch_size: tuple of integers defining the size of the patches in each dimension.
    - num_patches: number of random patches to extract.
    
    Returns:
    - A list of randomly cropped patches as numpy arrays.
    """
    data_shape = data.shape
    ndim = len(data_shape)
    
    # Ensure patch size fits within the data dimensions
    for dim in range(ndim):
        if patch_size[dim] > data_shape[dim]:
            raise ValueError(f"Patch size {patch_size[dim]} exceeds data dimension {data_shape[dim]} in dimension {dim}")
    
    patches = []
    
    for _ in range(num_patches):
        # Randomly select the starting point for each dimension
        start_coords = [random.randint(0, data_shape[dim] - patch_size[dim]) for dim in range(ndim)]
        
        # Create slices for the selected patch
        patch_slices = tuple(slice(start_coords[dim], start_coords[dim] + patch_size[dim]) for dim in range(ndim))
        
        # Extract the patch and add to the list
        patches.append(data[patch_slices])
    
    return patches


# %% ../nbs/01_data.ipynb 45
def save_patches_random(data_folder, gt_folder, output_folder, patch_size, num_patches):
    """
    Loads n-dimensional data from data_folder and gt_folder, generates random patches, and saves them into individual HDF5 files.
    Each HDF5 file will have datasets with the structure X/patch_idx and y/patch_idx.
    
    Parameters:
    - data_folder: Path to the folder containing data files (n-dimensional data).
    - gt_folder: Path to the folder containing ground truth (gt) files (n-dimensional data).
    - output_folder: Path to the folder where the HDF5 files will be saved.
    - patch_size: tuple of integers defining the size of the patches.
    - num_patches: number of random patches to extract per file.
    """
    
    # Ensure output folder exists
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    
    # Ensure the folders contain the same number of files
    data_files = sorted([f for f in os.listdir(data_folder) if f.endswith(('.npy', '.npz', '.png', '.tif', '.tiff'))])
    gt_files = sorted([f for f in os.listdir(gt_folder) if f.endswith(('.npy', '.npz', '.png', '.tif', '.tiff'))])
    
    if len(data_files) != len(gt_files):
        raise ValueError("The number of files in data_folder and gt_folder must be the same.")
    
    # Loop through the files in the folders with progress bar
    for data_file_name, gt_file_name in tqdm(zip(data_files, gt_files), total=len(data_files), desc="Processing files"):
        data_file_path = os.path.join(data_folder, data_file_name)
        gt_file_path = os.path.join(gt_folder, gt_file_name)
        
        # Load the images
        data = np.array(image_reader(data_file_path)[0])
        gt = np.array(image_reader(gt_file_path)[0])        
        if data.shape != gt.shape:
            raise ValueError(f"Shape mismatch between {data_file_name} and {gt_file_name}")
        
        # Extract random patches from both datasets
        data_patches_nd = extract_random_patches(data, patch_size, num_patches)
        gt_patches_nd = extract_random_patches(gt, patch_size, num_patches)
        
        # Create a new HDF5 file for this pair of files
        hdf5_filename = os.path.join(output_folder, f"{os.path.splitext(data_file_name)[0]}_random_patches.h5")
        
        with h5py.File(hdf5_filename, 'w') as hf:
            # Store each patch in a separate dataset with a progress bar for each file
            for patch_idx, (data_patch, gt_patch) in enumerate(tqdm(zip(data_patches_nd, gt_patches_nd), 
                                                                    total=num_patches, 
                                                                    desc=f"Saving random patches for {data_file_name}", 
                                                                    leave=False)):
                hf.create_dataset(f'X/{patch_idx}', data=data_patch)
                hf.create_dataset(f'y/{patch_idx}', data=gt_patch)
        

