# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_losses.ipynb.

# %% auto 0
__all__ = ['CombinedLoss', 'DiceLoss', 'FRCLoss', 'seventh_fourier_ring_correlation']

# %% ../nbs/03_losses.ipynb 3
from .core import store_attr

# %% ../nbs/03_losses.ipynb 4
import numpy as np

from monai.losses import SSIMLoss
import torch.nn as nn
from torch import sigmoid

from scipy.optimize import curve_fit

from .metrics import FRCMetric, get_fourier_ring_correlations


# %% ../nbs/03_losses.ipynb 7
class CombinedLoss:
    "losses combined"
    def __init__(self, spatial_dims=2, alpha=0.33, beta=0.33):
        store_attr()
        self.SSIM_loss = SSIMLoss(spatial_dims=spatial_dims)
        self.MSE_loss =  nn.MSELoss()
        self.MAE_loss =  nn.L1Loss()
        
    def __call__(self, pred, targ):
        return (1 - self.alpha - self.beta) * self.SSIM_loss(pred, targ) + self.alpha * self.MSE_loss(pred, targ) + self.beta * self.MAE_loss(pred, targ)
        

# %% ../nbs/03_losses.ipynb 9
class DiceLoss(nn.Module):

    """
    DiceLoss computes the Sørensen–Dice coefficient loss, which is often used 
    for evaluating the performance of image segmentation algorithms.

    The Dice coefficient is a measure of overlap between two samples. It ranges 
    from 0 (no overlap) to 1 (perfect overlap). The Dice loss is computed as 
    1 - Dice coefficient, so it ranges from 1 (no overlap) to 0 (perfect overlap).

    Attributes:
        smooth (float): A smoothing factor to avoid division by zero and ensure numerical stability.

    Methods:
        forward(inputs, targets):
            Computes the Dice loss between the predicted probabilities (inputs) 
            and the ground truth (targets).
    """

    def __init__(self, smooth=1):

        """
        Initializes the DiceLoss instance with a smoothing factor.

        Args:
            smooth (float): A smoothing factor to avoid division by zero and ensure numerical stability.
                            Default is 1.
        """
        super(DiceLoss, self).__init__()
        self.smooth = smooth

    def forward(self, inputs, targets):
        
        # Make sure the inputs are probabilities
        inputs = sigmoid(inputs)

        # Flatten tensors
        inputs = inputs.view(-1)
        targets = targets.view(-1)

        # Calculate the intersection
        intersection = (inputs * targets).sum()

        # Compute Dice Coefficient
        dice = (2. * intersection + self.smooth) / (inputs.sum() + targets.sum() + self.smooth)

        # Copmute dice loss
        loss = 1 - dice

        return loss
        

# %% ../nbs/03_losses.ipynb 13
def FRCLoss(image1, image2):

    """
    Compute the Fourier Ring Correlation (FRC) loss between two images.

    #### Args:
        - image1 (torch.Tensor): The first input image.
        - image2 (torch.Tensor): The second input image.

    #### Returns:
        - torch.Tensor: The FRC loss.
    """
    
    return (1 - FRCMetric(image1, image2))
    

# %% ../nbs/03_losses.ipynb 14
def seventh_fourier_ring_correlation(image1,image2):


    """
    Calculate the cutoff frequency at when Fourier ring correlation drops to 1/7.

    #### Args:
        - image1 (torch.Tensor): The first input image.
        - image2 (torch.Tensor): The second input image.

    #### Returns:
        - float: The cutoff frequency.
    """

    # Get y and x coordinates
    y, x = get_fourier_ring_correlations(image1, image2)

    # x -> frequency   y -> correlation
    x = x.numpy()
    y = y.numpy()


    # Exponential function to fit
    def exponential_func(x, a, b, c):
        return a * np.exp(-b * x) + c

    # Make fit
    params, _ = curve_fit(exponential_func, x, y, p0=[1, 1, 1])

    # Get Cutoff requency at 1/7
    cutoff_frequency = (exponential_func((1/7), *params))

    return cutoff_frequency
