# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_losses.ipynb.

# %% auto 0
__all__ = ['SSIMMetric', 'CombinedLoss', 'SSIM']

# %% ../nbs/02_losses.ipynb 4
from fastai.vision.all import *
from monai.losses import SSIMLoss


# %% ../nbs/02_losses.ipynb 6
class CombinedLoss:
    "losses combined"
    def __init__(self, spatial_dims=2, alpha=0.33, beta=0.33):
        store_attr()
        self.SSIM_loss = SSIMLoss(spatial_dims=spatial_dims)
        self.MSE_loss =  nn.MSELoss()
        self.MAE_loss =  nn.L1Loss()
        
    def __call__(self, pred, targ):
        return (1 - self.alpha - self.beta) * self.SSIM_loss(pred, targ) + self.alpha * self.MSE_loss(pred, targ) + self.beta * self.MAE_loss(pred, targ)

# %% ../nbs/02_losses.ipynb 11
def SSIM(x, y, spatial_dims=2):
    return 1 - SSIMLoss(spatial_dims)(x,y)

SSIMMetric = AvgMetric(SSIM)
