# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_metrics.ipynb.

# %% auto 0
__all__ = ['SSIMMetric', 'SSIM', 'FRCM']

# %% ../nbs/06_metrics.ipynb 3
from numpy import trapz
from fastai.vision.all import AvgMetric
from .losses import SSIMLoss, get_fourier_ring_correlations

# %% ../nbs/06_metrics.ipynb 4
def SSIM(x, y, spatial_dims=2):
    return 1 - SSIMLoss(spatial_dims)(x,y)

SSIMMetric = AvgMetric(SSIM)

# %% ../nbs/06_metrics.ipynb 5
def FRCM(image1, image2):


    """
    Compute the area under the Fourier Ring Correlation (FRC) curve between two images.

    #### Args:
        - image1 (torch.Tensor): The first input image.
        - image2 (torch.Tensor): The second input image.

    #### Returns:
        - float: The area under the FRC curve.
    """

    # Calculate the Fourier Ring Correlation and spatial frequency
    FRC, spatial_frequency = get_fourier_ring_correlations(image1, image2)

    # Convert to numpy
    FRC = FRC.numpy()
    spatial_frequency = spatial_frequency.numpy()
      
    # Compute the area under the curve using trapezoidal integration
    area = trapz(FRC, spatial_frequency)
    
    return area

