# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_nets.ipynb.

# %% auto 0
__all__ = ['DnCNN']

# %% ../nbs/04_nets.ipynb 6
from fastai.vision.all import ConvLayer, Lambda, MaxPool, NormType, nn, np
from torch import cat as torch_cat
from torch import Tensor as torch_Tensor
import torch.nn.functional as F
import torch.nn as nn
from monai.networks.blocks import Convolution
from monai.networks.layers.factories import Act, Norm, Pool
from monai.networks.nets import resnet
from monai.utils import set_determinism
from torchvision.models.resnet import resnet50 #, resnet18

from monai.networks.nets import BasicUNet, AttentionUnet, DynUNet, UNet, BasicUNet, ResNet, ResNetFeatures

from dataclasses import dataclass, field
from typing import List, Tuple, Optional, Union

from .core import attributesFromDict

# %% ../nbs/04_nets.ipynb 9
class DnCNN(nn.Module):
    def __init__(self, channels, num_of_layers=9, features=64, kernel_size=3):
        super(DnCNN, self).__init__()
        padding = 1
        layers = []
        layers.append(ConvLayer(channels, features,
                      ks=kernel_size, padding=padding, norm_type=None))
        for _ in range(num_of_layers-2):
            layers.append(ConvLayer(features, features,
                          ks=kernel_size, padding=padding))
        layers.append(nn.Conv2d(in_channels=features, out_channels=channels,
                      kernel_size=kernel_size, padding=padding, bias=False))
        self.dncnn = nn.Sequential(*layers)

    def forward(self, x):
        residual = self.dncnn(x)
        denoised = x - residual
        return denoised
