# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_transforms.ipynb.

# %% auto 0
__all__ = ['Resample', 'RandCameraNoise', 'ScaleIntensityRange', 'ScaleIntensityPercentiles', 'RandCrop2D', 'RandCropND',
           'RandFlip', 'RandRot90']

# %% ../nbs/05_transforms.ipynb 3
import numpy as np
from fastai.vision.all import *
from fastai.data.all import *
from monai.transforms import SpatialCrop, Flip, Rotate90, Spacing
from numpy import percentile, isscalar, float32 as np_float32

# %% ../nbs/05_transforms.ipynb 5
class Resample(Spacing):
    """
    A subclass of Spacing that handles image resampling based on specified sampling factors or voxel dimensions.
    
    The `Resample` class inherits from `Spacing` and provides a flexible way to adjust the spacing (voxel size) of images by specifying either a sampling factor or explicitly providing new voxel dimensions.
    
    Args:
        sampling (int, optional): Sampling factor for isotropic resampling. Default is 1, indicating no change in resolution.
        **kwargs: Additional keyword arguments that can include 'pixdim' to specify custom voxel dimensions.
        
    Attributes:
        pixdim (list or tuple): The voxel dimensions of the image after resampling. If not provided during initialization, this will be determined based on the sampling factor and original image properties.
    
    Methods:
        None
    
    Example Usage:
        # Creating a Resample object with a specified sampling factor
        resampler = Resample(sampling=2)
        
        # Creating a Resample object with custom voxel dimensions
        resampler = Resample(**kwargs={'pixdim': [1.5, 1.5, 3]})
    """
    
    def __init__(self, sampling, **kwargs):
        """
        Initializes the Resample class instance.
        
        Args:
            sampling (int, optional): Sampling factor for isotropic resampling. Default is 1.
            **kwargs: Additional keyword arguments that can include 'pixdim' to specify custom voxel dimensions.
            
        If 'pixdim' is provided in kwargs, it will be used directly; otherwise, the sampling factor will determine the new voxel dimensions.
        
        The Spacing class from which Resample inherits is initialized with either the provided pixdim or calculated based on the sampling factor and original image properties.
        """
        if 'pixdim' in kwargs:
            super().__init__(**kwargs)
        else:
            super().__init__(sampling, **kwargs)


# %% ../nbs/05_transforms.ipynb 9
def RandCameraNoise(input_image, qe=0.7, gain=2, exp_time=0.1, dark_current=0.06, readout=2.5, bitdepth=16, offset=100, seed=42, simulation=False, camera='cmos', gain_variance=.1, offset_variance=5):
    """
    Simulates camera noise by adding Poisson shot noise, dark current noise, and optionally CMOS fixed pattern noise.
    
    Args:
        input_image (numpy.ndarray): The original image as a NumPy array.
        qe (float, optional): Quantum efficiency of the camera (0 to 1). Default is 0.7.
        gain (float or numpy.ndarray, optional): Camera gain factor. If an array, it should be broadcastable with input_image shape. Default is 2.
        exp_time (float, optional): Exposure time in seconds. Default is 0.1.
        dark_current (float, optional): Dark current per pixel in electrons/second. Default is 0.06.
        readout (float, optional): Readout noise standard deviation in electrons. Default is 2.5.
        bitdepth (int, optional): Bit depth of the camera output. Default is 16.
        offset (int or float, optional): Offset value to add to each pixel after conversion to ADU. Default is 100.
        seed (int, optional): Seed for random number generator for reproducibility. Default is 42.
        simulation (bool, optional): If True, assumes input_image is already in units of photons and does not convert from electrons. Default is False.
        camera (str, optional): Specifies the type of camera ('cmos' or any other). Used to add CMOS fixed pattern noise if 'cmos' is specified. Default is 'cmos'.
        gain_variance (float, optional): Variance for the gain noise in CMOS cameras. Only applicable if camera type is 'cmos'. Default is 0.1.
        offset_variance (float, optional): Variance for the offset noise in CMOS cameras. Only applicable if camera type is 'cmos'. Default is 5.
    
    Returns:
        numpy.ndarray: The noisy image as a NumPy array with dimensions of input_image.
    """
    rs = np.random.RandomState(seed=seed)
    
    # If simulation mode, assume input_image is already in units of photons
    if not simulation:
        input_photons = input_image / gain / qe
    else:
        input_photons = input_image
    
    # Add Poisson shot noise to the input image in terms of photons or directly as electrons
    photons = rs.poisson(input_photons, size=input_photons.shape)
    electrons = qe * photons  # Convert photons to electrons using quantum efficiency (qe)
    
    # Add dark current noise
    dark_noise = rs.poisson(dark_current * exp_time, size=electrons.shape)
    electrons += dark_noise  # Convert dark current from rate to number of events
    
    # Add readout noise
    read_noise = rs.normal(scale=readout**2, size=electrons.shape)
    electrons += read_noise  # Adding normal distributed noise based on readout standard deviation
    
    if camera == 'cmos':
        # Add gain noise in CMOS cameras
        gain_noise = rs.normal(scale=gain_variance, size=electrons.shape)
        # Add offset noise and fixed pattern noise in CMOS cameras
        offset_noise = rs.normal(scale=offset_variance, size=electrons.shape) + rs.normal(scale=offset_variance, size=electrons.shape[0])
        gain += gain_noise  # Adjusting the gain by adding normally distributed noise
        offset += offset_noise  # Adding offset noise and fixed pattern noise
    
    max_adu = 2**bitdepth - 1  # Calculate maximum possible ADU value for the given bit depth
    adu = (electrons * gain) + offset  # Convert electrons to ADU, then add offset
    adu[adu > max_adu] = max_adu  # Clip values above full scale to avoid overflow
    
    # return adu.astype(np.uint8) if bitdepth <= 8 else adu.astype(np.uint8) 
    return adu


# %% ../nbs/05_transforms.ipynb 13
def ScaleIntensityRange(x, mi, ma, eps=1e-20, dtype=np_float32):
    if dtype is not None:
        x = x.astype(dtype, copy=False)
        mi = dtype(mi) if isscalar(mi) else mi.astype(dtype, copy=False)
        ma = dtype(ma) if isscalar(ma) else ma.astype(dtype, copy=False)
        eps = dtype(eps)
        x = (x - mi) / (ma - mi + eps)
    return x

# %% ../nbs/05_transforms.ipynb 14
def ScaleIntensityPercentiles(x, pmin=3, pmax=99.8, axis=None, eps=1e-20, dtype=np_float32):
    """Percentile-based image normalization."""

    mi = percentile(x, pmin, axis=axis, keepdims=True)
    ma = percentile(x, pmax, axis=axis, keepdims=True)
    return ScaleIntensityRange(x, mi, ma, eps=eps, dtype=dtype)


# %% ../nbs/05_transforms.ipynb 18
def _process_sz(size, ndim=3):
    if isinstance(size,int): 
        size=(size,)*ndim
    return fastuple(size)

def _get_sz(x):
    if isinstance(x, tuple): x = x[0]
    if not isinstance(x, Tensor): return fastuple(x.size)
    return fastuple(getattr(x, 'img_size', getattr(x, 'sz', (x.shape[1:])))) # maybe it should swap x and y axes 

# %% ../nbs/05_transforms.ipynb 21
class RandCrop2D(RandTransform):
    "Randomly crop an image to `size`"
    split_idx,order = None,1
    def __init__(self, 
        size:int|tuple, # Size to crop to, duplicated if one value is specified
        lazy = False,   # a flag to indicate whether this transform should execute lazily or not. Defaults to False
        **kwargs
    ):
        size = _process_sz(size, ndim=2)
        store_attr()
        super().__init__(**kwargs)

    def before_call(self, 
        b, 
        split_idx:int # Index of the train/valid dataset
    ):
        "Randomly positioning crop if train dataset else center crop"
        self.orig_sz = _get_sz(b)
        if split_idx: self.ctr = (self.orig_sz)//2
        else:
            wd = self.orig_sz[0] - self.size[0]
            hd = self.orig_sz[1] - self.size[1]
            w_rand = (wd, -1) if wd < 0 else (0, wd)
            h_rand = (hd, -1) if hd < 0 else (0, hd)
            self.ctr = fastuple(random.randint(*w_rand)+self.size[0]//2, random.randint(*h_rand)+self.size[1]//2)

    def encodes(self, x):
        return SpatialCrop(roi_center=self.ctr, roi_size=self.size, lazy=self.lazy)(x)

# %% ../nbs/05_transforms.ipynb 22
class RandCropND(RandTransform):
    """
    Randomly crops an ND image to a specified size.

    This transform randomly crops an ND image to a specified size during training and performs
    a center crop during validation. It supports both 2D and 3D images and videos, assuming
    the first dimension is the batch dimension.

    Args:
        size (int or tuple): The size to crop the image to. this can have any number of dimensions. 
                             If a single value is provided, it will be duplicated for each spatial 
                             dimension, up to a maximum of 3 dimensions.
        **kwargs: Additional keyword arguments to be passed to the parent class.
    """

    split_idx,order = None,1
        
    def __init__(self, size: int | tuple, # Size to crop to, duplicated if one value is specified
                 lazy = False,            # a flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        size = _process_sz(size)
        store_attr()
        super().__init__(**kwargs)

    def before_call(self, b, split_idx: int):
        "Randomly position crop if train dataset else center crop"
        self.orig_sz = _get_sz(b)
        if split_idx:
            self.tl = tuple((osz - sz) // 2 for osz, sz in zip(self.orig_sz, self.size))
            self.br = tuple((osz + sz) // 2 for osz, sz in zip(self.orig_sz, self.size))
        else:
            tl = [] # top-left corner
            br = [] # bottom-right corner
            # Calculate top-left and bottom-right corner coordinates for random crop
            for osz, sz in zip(self.orig_sz, self.size):
                w_dif = osz - sz
                if w_dif < 0:
                    w_rand = (0, 0) # No random cropping if input size is smaller than crop size
                    sz = osz # Adjust crop size to match input size
                else:
                    w_rand = (0, w_dif)
                rnd = random.randint(*w_rand)
                tl.append(rnd)
                br.append(rnd + sz)
            self.tl = fastuple(*tl)
            self.br = fastuple(*br)

    def encodes(self, x):
        "Apply spatial crop transformation to the input image."
        return SpatialCrop(roi_start=self.tl, roi_end=self.br, lazy=self.lazy)(x)
    

# %% ../nbs/05_transforms.ipynb 24
class RandFlip(RandTransform):
    """
    Randomly flips an ND image over a specified axis.

    """

    split_idx,order = None,1
        
    def __init__(self, 
                 prob = 0.1,            # Probability of flipping
                 spatial_axis = None,   # Spatial axes along which to flip over. Default is None. The default axis=None will flip over all of the axes of the input array. 
                                        # If axis is negative it counts from the last to the first axis. If axis is a tuple of ints, flipping is performed on all of the axes specified in the tuple.
                 ndim = 2,
                 lazy = False,          # Flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        store_attr()
        super().__init__(**kwargs)

    def before_call(self, b, split_idx: int):
        if split_idx:
            self.flip = 0
        else:
            self.flip = np.random.choice([0, 1], p=[1-self.prob, self.prob])
        if self.spatial_axis is None:
            self.spatial_axis = np.random.choice(np.arange(self.ndim), size=np.random.randint(1, self.ndim+1), replace=False, p=None)
            
    def encodes(self, x):
        if self.flip:
            return Flip(spatial_axis=self.spatial_axis, lazy=self.lazy)(x)
        else:
            return x

# %% ../nbs/05_transforms.ipynb 26
class RandRot90(RandTransform):
    """
    Randomly rotate an ND image by 90 degrees in the plane specified by axes.

    """

    split_idx,order = None,1
        
    def __init__(self, 
                 prob = 0.1,            # Probability of rotating
                 max_k = 3,             # Max number of times to rotate by 90 degrees
                 spatial_axes = (0, 1),   # Spatial axes along which to rotate. Default: (0, 1), this is the first two axis in spatial dimensions.
                 ndim = 2,
                 lazy = False,          # Flag to indicate whether this transform should execute lazily or not. Defaults to False
                 **kwargs):
        store_attr()
        super().__init__(**kwargs)

    def before_call(self, b, split_idx: int):
        if split_idx:
            self.rot90 = 0
        else:
            self.rot90 = np.random.choice([0, 1], p=[1-self.prob, self.prob])
            self.k = 1 + np.random.randint(self.max_k)
        # if self.spatial_axes is None:
        #     self.spatial_axes = np.random.choice(np.arange(self.ndim), size=np.random.randint(1, self.ndim+1), replace=False, p=None)
            
    def encodes(self, x):
        if self.rot90:
            return Rotate90(k=self.k, spatial_axes=self.spatial_axes, lazy=self.lazy)(x)
        else:
            return x
