name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
      - nightly

permissions:
  contents: write  # Ensure the workflow can write to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _docs
        publish_branch: gh-pages
